### ISSUE TITLE
更新插件提示文件权限问题

### ISSUE THREAD

**Issue by CZT0** [sunxiyuan/wp-china-yes#1]
在更新WP User Avatar时发生了错误：因为我们不能复制一些文件，升级未被安装。这通常是因为存在不一致的文件权限。
请问这个是因为我的wordpress设置问题还是插件的原因
非常感谢创造了此插件

**Comment by sunxiyuan** [comment]
这个已经很明显是系统目录权限的问题了，并不是插件的问题。如果不会设置权限可以直接改成777

**Comment by CZT0** [comment]
十分感谢，问题已经解决
