### ISSUE TITLE
Is wp-china-yes available in English?

### ISSUE THREAD

**Issue by jagottsicher** [sunxiyuan/wp-china-yes#11]
Is wp-china-yes available in English?

And if it is not, is is prepared to be translateable?

**Comment by sunxiyuan** [comment]
Is there a GFW like network management and control method in other parts of the world? If so, I will actively promote international translation support.

**Comment by jagottsicher** [comment]
See, not worth the effort if mainly Chinese users will use this plugin, and not many foreigners in China like me! :-) 

BTW: a big THANKS for your work. This plugin helps me alot in administrational work for wordpress in China! big THUMBS UP!  Great job! Please stay healthy!
