### ISSUE TITLE
Free also for commercial use?

### ISSUE THREAD

**Issue by jagottsicher** [sunxiyuan/wp-china-yes#12]
You say:

> 这个是一个公益项目，我始终都不会以任何借口对插件、加速节点的使用权等进行收费。

The translation for that is not clear. Does that mean you also allow commercial use?
For example if you are operating several servers in China mainland behind GFW?

**Comment by sunxiyuan** [comment]
This is a free plugin for everyone.All servers are provided by volunteers.If you like,You can also provide servers out of China for others using.

**Comment by jagottsicher** [comment]
Thanks!
