### ISSUE TITLE
Does wp-china-yes support connection to update Third-Party Themes

### ISSUE THREAD

**Issue by jagottsicher** [sunxiyuan/wp-china-yes#13]
Does wp-china-yes support connection to update Third-Party Themes?

Especially Avada from Themepunch and the Fusion servers (theme-related plugins and features) are very interesting to work.

**Comment by sunxiyuan** [comment]
This is a free plugin for everyone.All servers are provided by volunteers.If you like,You can also provide servers out of China for others using.

**Comment by sunxiyuan** [comment]
Do you want to ask WP-China-Yes whether it supports updates to themes that are not hosted by agents in the official WordPress repository (they use their own servers for updates).
If so,I'm sorry that It can't do this now.But I will support it in the future versions

**Comment by jagottsicher** [comment]
Understand! Thanks!
