### ISSUE TITLE
Resolving also https domains properly

### ISSUE THREAD

**Issue by jagottsicher** [sunxiyuan/wp-china-yes#14]
Is the proxy resolving https/ssl domains properly and forwarding/redirecting requests e.g. to servers like https://updates.theme-fusion.com/ and similar?

**Comment by sunxiyuan** [comment]
Sorry,I don't understand your meaning.Can you description it more clearly?

**Comment by jagottsicher** [comment]
Was ansered in another issue. I thought it does not work because of wrong resolving the hostname, but it does not work, because it is a third-party theme (not from wordpress)
