### ISSUE TITLE
cURL error 18: transfer closed with xxxxxxxxx bytes remaining to read

### ISSUE THREAD

**Issue by w4o** [sunxiyuan/wp-china-yes#15]
![image](https://user-images.githubusercontent.com/13061300/78090150-ee497b00-73fb-11ea-9c72-de15c74e93b2.png)

**Comment by sunxiyuan** [comment]
感谢反馈，我已知此问题，正在排查中

**Comment by w4o** [comment]
可以先看下硬盘是否有足够空间；我在数次莫名其妙的错误中被硬盘空间坑过

**Comment by sunxiyuan** [comment]
这个现在确定是CDN的问题。
我今天早上把部分域名从百度云加速迁移到又拍云了，这会又拍云的技术在排查了。
我怀疑是触发了他们什么安全规则，导致被拦截了，其他资源下载都是正常的，就是这个更新包不行。

**Comment by w4o** [comment]
@sunxiyuan 是的，刚刚我是先更新的 `wordpress-seo` 插件，后更新的wp程序；插件是正常更新的，只有wp程序不能更新。

**Comment by sunxiyuan** [comment]
该问题已修复，是因为我配置的源站不支持断点续传，然后又拍云的CDN一直是用断点的方式分段缓存，于是就报错了……把分段缓存关掉就好了。
百度云加速没问题是因为百度不支持分段缓存。
