### ISSUE TITLE
主题插件无法下载

### ISSUE THREAD

**Issue by wleagle** [sunxiyuan/wp-china-yes#16]
插件不错，wp的插件都能下载了。但the7主题里的插件，下载总是提示“下载失败。 cURL error 77:” 有办法解决吗？

**Comment by sunxiyuan** [comment]
要不你再试一下？我刚刚在迁移api使用的CDN，可能影响到你了。这会已经已经迁移好了，你再试下，如果还不行的话就提供一个你的主题的安装包给我，然后我调试一下。

**Comment by sunxiyuan** [comment]
如果已经可以了的话记得关闭一下issue
