### ISSUE TITLE
翻译更新不成功

### ISSUE THREAD

**Issue by w4o** [sunxiyuan/wp-china-yes#18]
wp后台提示有翻译更新，点击更新后提示更新成功，如图：

![image](https://user-images.githubusercontent.com/13061300/78328680-50e47780-75b2-11ea-8756-ea059110376a.png)

但实际是没有更新成的；两个现象可以证明：

1.刷新后再次提示该更新

![image](https://user-images.githubusercontent.com/13061300/78328749-7d988f00-75b2-11ea-89bd-1473f7cc36e9.png)

2.因为我的wp是git管理，执行更新操作后发现服务器没有文件被更改

![image](https://user-images.githubusercontent.com/13061300/78328797-a1f46b80-75b2-11ea-9a55-c440953ab0c1.png)

**建议后期考虑增加调试日志，可以根据`WP_DEBUG`配置来输出日志，方便排查问题**

**Comment by sunxiyuan** [comment]
感谢反馈，我调试一下

**Comment by sunxiyuan** [comment]
该问题已定位。
翻译文件请求的URI是`/translation/plugin/wp-mail-smtp/1.9.0/zh_CN.zip`
该文件从WordPress官方服务器请求的时候响应头中会包含content-disposition头来指定文件名为“wp-mail-smtp-1.9.0-zh_CN.zip”。
目前我配置的社区源将各种压缩包都迁移到了又拍云存储上，从云存储上取到的数据丢失了content-disposition响应头，所以最终下载下来的文件名是“zh_CN.zip”这就导致了无法更新的情况。

**Comment by sunxiyuan** [comment]
问题已修复——翻译文件不再迁移到云存储中保存，直接在CDN节点上缓存。
这几天我对社区源做了大量调整，难免会存在一些bug，还望积极反馈问题。

**Comment by sunxiyuan** [comment]
关于调试日志，目前程序代码非常简单，最新版本有效代码只有三十几行，基本不会引起什么错误。有错误通常都是社区源配置问题引起的，随着问题一点点被修复，社区源服务会越来越稳定。
