### ISSUE TITLE
增加刷新按钮或者增加缓存有效期。

### ISSUE THREAD

**Issue by sy-records** [sunxiyuan/wp-china-yes#2]
比如插件存在更新时，还是缓存的旧的，导致更新失败。
或者有更新，缓存的旧的，导致下载的旧版本。

**Comment by sunxiyuan** [comment]
是这样的，如果插件或主题有更新，你将会在2小时内接收到更新。主题和插件的文件缓存期是7天，但是wp使用svn管理插件和主题，每个新版本的发布都会对应一个新的tag，同时wp的主服务器会根据tag为每个版本生成不同的zip压缩包，这样每个文件的url都是不同的，并不会出现插件更新了下载下来还是旧的的问题
