### ISSUE TITLE
我刚升级了版本发现自带的编辑器出现错误，不知道是不是我自己的问题

### ISSUE THREAD

**Issue by WangShuoran** [sunxiyuan/wp-china-yes#4]
![image](https://user-images.githubusercontent.com/43474491/76587869-42a9bb00-6520-11ea-8305-bb8ef384239f.png)

**Comment by WangShuoran** [comment]
刚看了一下commit，说这个版本不适合生产版本，Cry.....

**Comment by sunxiyuan** [comment]
加我qq：1642491905，我调试下看看，目前这个问题还没人反馈。这个版本已经经过测试了，可以使用了的。
