### ISSUE TITLE
any documentation to use custom cdn?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [sunxiyuan/wp-china-yes#5]
See https://www.ibadboy.net/archives/3349.html

**Comment by sunxiyuan** [comment]
Yes

**Comment by zhaofeng-shu33** [comment]
I think the reverse proxy is crucial but the article in the link does not give some common practice on this. For example, I have an Apache overseas server. How can I configure my Apache to do reverse proxy for `wp-china-yes` to work?
