### ISSUE TITLE
security issue using standalone `api.php`.

### ISSUE THREAD

**Issue by zhaofeng-shu33** [sunxiyuan/wp-china-yes#7]
For a wordpress plugin, it is forbidden to open a second entrypoint which can be accessed directly by
visiting `[root_url]/wp-content/plugins/plugin_name/api.php`. Therefore, at the beginning of each file,
`if not defined ABSPATH, die immediately`. Wordpress provides server side ajax framework, which can replace bad practice in `api.php`. See the documentation of function `add_action( 'wp_ajax_xxx')`

**Comment by sunxiyuan** [comment]
This problem is real,I will fix it soon.Thx your advice.

**Comment by sunxiyuan** [comment]
This issue has been solved. Thanks again for your reminding. Thank you a lot!
