### ISSUE TITLE
Mirror Discussion; its prospect and destiny

### ISSUE THREAD

**Issue by zhaofeng-shu33** [sunxiyuan/wp-china-yes#8]
An abandoned project: https://github.com/bluehost/pluginmirror/issues/11

**Comment by sunxiyuan** [comment]
不好意思，我词汇量有限，看了你的个人主页，发现咱们是老乡，那我索性直接回中文了。
这几天看到你在关注这个项目，我感到很荣幸，我不确定这个issue的意思是不是想讨论一下WP-China-Yes项目日后的发展方向。
我先假设是这个意思，并就此发表一下我的观点。
不知道你有没有发现，对于国内WordPress生态来说，如今有一个大好的进行变革的机遇——429问题。
所谓乱世出英雄，我想做的就是要在这场瘟疫（429问题）中将解药（WP-China-Yes）推广开，并争取在瘟疫过后能把解药变为粮食（类似Linux镜像站），使“使用WordPress就要切换到中国源”的这个概念深入人心，最后谋求和官方达成合作，直接预置插件，以求彻底改善国内WordPress使用体验。
想和和平时期达到这样的成果是非常不容易的，唯有乱世才有可能一搏。
往严重一点说，这是一个“历史时期”，抓住了，就能发起一场国内WordPress生态的变革。
所以我感觉如今项目发展的重中之重就是如何抓好这个机遇，如何利用好429问题的时间窗口让更多人了解到这个项目。
只有当受众足够广了，后面再推进其他项目才容易推开，否则所做的一切努力就没有曝光机会，更不会被大家了解到。
人生苦短，只能尽量谨慎的把握好每个机会，以求将生命之火产生的光辉与温度散发于人间。

**Comment by zhaofeng-shu33** [comment]
I agree with you. It seems using your own CDN and reverse proxy resource is not a good choice. Maybe some support from Chinese University Mirror? I am not sure.

**Comment by sunxiyuan** [comment]
是的，我有思考过这个问题。如今的解决方案只是在各种制约因素中寻找平衡的一个过度方案，存在很多不足。举个例子——CDN无法预缓存所有资源，势必会有一些访问请求需要被回源处理，回源的过程中就会有损用户体验。

开源镜像站的运营思路，Linux、NPM等一批老前辈已经给出了比较明确的线路了，就是你说的寻求大学支持，另外还有部分企业的支持。
不过，建立起“镜像站”需要WordPress官方配合提供类似rsync这种数据同步的手段，否则在技术上将难以实现。我设想是后面这个项目用户规模足够大了，可以证明镜像站点是一个“刚需”了，再与官方交涉。

“pluginmirror”这个项目我需要一点时间研究一下他的实现原理，目前就我掌握的资料来看，想完全实现类似Linux开源镜像站的那种东西很难，同时又由于时间紧迫，所以我折中的采用了反代+CDN的方式来尝试解决这个问题。

如果你对pluginmirror项目的原理已经有了解了，我很希望你能分享一下

**Comment by zhaofeng-shu33** [comment]
pluginmirror is a dead project. I do not know its mechanism either.
